# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Hendrik.Siemens\Documents\GitHub\TBDiC\gui\setup_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(530, 646)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.wizardPage1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 494, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAutoFillBackground(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.checkBox_autodetectTimezone = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_autodetectTimezone.setAutoFillBackground(True)
        self.checkBox_autodetectTimezone.setObjectName("checkBox_autodetectTimezone")
        self.horizontalLayout_3.addWidget(self.checkBox_autodetectTimezone)
        self.comboBox_selectTimezone = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_selectTimezone.setObjectName("comboBox_selectTimezone")
        self.comboBox_selectTimezone.addItem("")
        self.comboBox_selectTimezone.addItem("")
        self.comboBox_selectTimezone.addItem("")
        self.comboBox_selectTimezone.addItem("")
        self.comboBox_selectTimezone.addItem("")
        self.comboBox_selectTimezone.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_selectTimezone)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        Wizard.addPage(self.wizardPage2)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)
        Wizard.setTabOrder(self.pushButton_2, self.checkBox_autodetectTimezone)
        Wizard.setTabOrder(self.checkBox_autodetectTimezone, self.comboBox_selectTimezone)
        Wizard.setTabOrder(self.comboBox_selectTimezone, self.pushButton_3)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.label.setText(_translate("Wizard", "Select a path for the database:"))
        self.pushButton_2.setText(_translate("Wizard", "Open file dialog"))
        self.label_3.setText(_translate("Wizard", "Set the timezone you\'re in:"))
        self.checkBox_autodetectTimezone.setText(_translate("Wizard", "Auto detect timezone"))
        self.comboBox_selectTimezone.setItemText(0, _translate("Wizard", "UTC"))
        self.comboBox_selectTimezone.setItemText(1, _translate("Wizard", "Europe / London"))
        self.comboBox_selectTimezone.setItemText(2, _translate("Wizard", "Europe / Berlin"))
        self.comboBox_selectTimezone.setItemText(3, _translate("Wizard", "Europe / Paris"))
        self.comboBox_selectTimezone.setItemText(4, _translate("Wizard", "Europe / Moscow"))
        self.comboBox_selectTimezone.setItemText(5, _translate("Wizard", "Asia / Tokyo"))
        self.label_2.setText(_translate("Wizard", "TextLabel"))
        self.pushButton_3.setText(_translate("Wizard", "PushButton"))
